name: Release

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release type
        options:
          - major
          - minor
          - patch
          - rc
          - beta
          - alpha

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      RELEASE_TYPE: ${{ github.event.inputs.release_type }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Install cargo-release
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-release
          version: latest
      - name: Cargo login
        run: |
          cargo login $CARGO_TOKEN
      - name: Dry-run cargo release
        run: |
          cargo release --workspace ${RELEASE_TYPE:-alpha} --exclude ethers-wasm
      - name: Publish release
        run: |
          cargo release --workspace ${RELEASE_TYPE:-alpha} --exclude ethers-wasm --execute --no-confirm
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm i semver
      - name: Install git-cliff
        uses: actions-rs/install@v0.1
        with:
          crate: git-cliff
          version: latest
      - name: Publish changelog
        run: |
          current_version=$(git tag --contains HEAD -l "v*" | head -1)
          from_version=$(node .github/workflows/release-tag-from.js $current_version)
          echo from $from_version to $current_version

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "tag exists, can generate changelog";
          else
            echo "tag does not exist, cannot generate changelog, publish github release manually"
            exit 0
          fi

          git cliff $from_version..$current_version > GENERATED_CHANGELOG.md
          cat GENERATED_CHANGELOG
