name: Release

on:
  schedule:
    - cron: "0 0 * * 0"

  push:
    branches:
      - master
      - ci-release-test
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release type
        options:
          - major
          - minor
          - patch
          - release
          - rc
          - beta
          - alpha

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      RELEASE_TYPE: ${{ github.event.inputs.release_type }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Install cargo-release
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-release
          version: latest
          use-tool-cache: true
      - name: cargo-login
        run: |
          cargo login $CARGO_TOKEN
      - name: dry-run cargo release
        run: |
          cargo release --workspace ${RELEASE_TYPE:-alpha} --exclude ethers-wasm
      - name: release
        run: |
          cargo release --workspace ${RELEASE_TYPE:-alpha} --exclude ethers-wasm --execute --no-confirm

